import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testDir, "..", "..");

test("post-merge script rebuilds artifacts without forcing db push", async () => {
  const script = await readFile(path.join(repoRoot, "scripts", "post-merge.sh"), "utf8");

  assert.match(script, /pnpm run build/);
  assert.doesNotMatch(script, /pnpm\s+--filter\s+db\s+push/);
});

test("replit artifact metadata files are removed so root .replit stays the only deployment entrypoint", async () => {
  const artifactTomls = [
    path.join(repoRoot, "artifacts", "api-server", ".replit-artifact", "artifact.toml"),
    path.join(repoRoot, "artifacts", "status-page", ".replit-artifact", "artifact.toml"),
  ];

  for (const artifactToml of artifactTomls) {
    await assert.rejects(
      access(artifactToml),
      /ENOENT/,
      `${artifactToml} should not exist in the repo`,
    );
  }
});

test(".gitignore excludes replit artifact metadata regenerated by the platform", async () => {
  const gitignore = await readFile(path.join(repoRoot, ".gitignore"), "utf8");

  assert.match(gitignore, /^artifacts\/api-server\/\.replit-artifact\/$/m);
  assert.match(gitignore, /^artifacts\/status-page\/\.replit-artifact\/$/m);
});

test("mockup sandbox is removed so deployment-focused artifacts stay unambiguous", async () => {
  await assert.rejects(
    access(path.join(repoRoot, "artifacts", "mockup-sandbox", "package.json")),
    /ENOENT/,
  );
});

test("root typecheck only targets deployment-critical workspace packages", async () => {
  const rootPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  const typecheck = rootPackageJson.scripts?.["typecheck"] || "";

  assert.match(typecheck, /@workspace\/api-server/);
  assert.match(typecheck, /@workspace\/status-page/);
  assert.match(typecheck, /@workspace\/scripts/);
  assert.doesNotMatch(typecheck, /\.\/artifacts\/\*\*/);
  assert.doesNotMatch(typecheck, /mockup-sandbox/);
});

test("root package scripts stay focused on direct deployment entrypoints", async () => {
  const rootPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  assert.ok(rootPackageJson.scripts?.["dev"]);
  assert.ok(rootPackageJson.scripts?.["build"]);
  assert.ok(rootPackageJson.scripts?.["start"]);
  assert.ok(rootPackageJson.scripts?.["typecheck"]);
  assert.equal(rootPackageJson.scripts?.["build:deploy"], undefined);
  assert.equal(rootPackageJson.scripts?.["typecheck:libs"], undefined);
});

test("workspace package list only includes the two deployable artifacts", async () => {
  const workspaceYaml = await readFile(path.join(repoRoot, "pnpm-workspace.yaml"), "utf8");

  assert.match(workspaceYaml, /^  - artifacts\/api-server$/m);
  assert.match(workspaceYaml, /^  - artifacts\/status-page$/m);
  assert.doesNotMatch(workspaceYaml, /^  - artifacts\/\*$/m);
  assert.doesNotMatch(workspaceYaml, /mockup-sandbox/);
});

test("lockfile no longer advertises mockup sandbox as a workspace importer", async () => {
  const lockfile = await readFile(path.join(repoRoot, "pnpm-lock.yaml"), "utf8");

  assert.doesNotMatch(lockfile, /^  artifacts\/mockup-sandbox:$/m);
});

test(".replitignore excludes local planning notes from deployment payloads", async () => {
  const replitignore = await readFile(path.join(repoRoot, ".replitignore"), "utf8");

  assert.match(replitignore, /^task_plan\.md$/m);
  assert.match(replitignore, /^findings\.md$/m);
  assert.match(replitignore, /^progress\.md$/m);
});

test("scripts package does not expose placeholder commands unrelated to deployment", async () => {
  const scriptsPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "scripts", "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  assert.equal(scriptsPackageJson.scripts?.["hello"], undefined);
});
