import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testDir, "..", "..");

test("post-merge script rebuilds artifacts without forcing db push", async () => {
  const script = await readFile(path.join(repoRoot, "scripts", "post-merge.sh"), "utf8");

  assert.match(script, /pnpm run build/);
  assert.doesNotMatch(script, /pnpm\s+--filter\s+db\s+push/);
});

test("replit artifact metadata files are removed so root .replit stays the only deployment entrypoint", async () => {
  const artifactTomls = [
    path.join(repoRoot, "artifacts", "api-server", ".replit-artifact", "artifact.toml"),
    path.join(repoRoot, "artifacts", "status-page", ".replit-artifact", "artifact.toml"),
  ];

  for (const artifactToml of artifactTomls) {
    await assert.rejects(
      access(artifactToml),
      /ENOENT/,
      `${artifactToml} should not exist in the repo`,
    );
  }
});

test(".gitignore excludes replit artifact metadata regenerated by the platform", async () => {
  const gitignore = await readFile(path.join(repoRoot, ".gitignore"), "utf8");

  assert.match(gitignore, /^artifacts\/api-server\/\.replit-artifact\/$/m);
  assert.match(gitignore, /^artifacts\/status-page\/\.replit-artifact\/$/m);
});
