import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testDir, "..", "..");

test("post-merge script rebuilds artifacts without forcing db push", async () => {
  const script = await readFile(path.join(repoRoot, "scripts", "post-merge.sh"), "utf8");

  assert.match(script, /pnpm run build/);
  assert.doesNotMatch(script, /pnpm\s+--filter\s+db\s+push/);
});

test("replit artifact metadata files are removed so root .replit stays the only deployment entrypoint", async () => {
  const artifactTomls = [
    path.join(repoRoot, "artifacts", "api-server", ".replit-artifact", "artifact.toml"),
    path.join(repoRoot, "artifacts", "status-page", ".replit-artifact", "artifact.toml"),
  ];

  for (const artifactToml of artifactTomls) {
    await assert.rejects(
      access(artifactToml),
      /ENOENT/,
      `${artifactToml} should not exist in the repo`,
    );
  }
});

test(".gitignore excludes replit artifact metadata regenerated by the platform", async () => {
  const gitignore = await readFile(path.join(repoRoot, ".gitignore"), "utf8");

  assert.match(gitignore, /^artifacts\/api-server\/\.replit-artifact\/$/m);
  assert.match(gitignore, /^artifacts\/status-page\/\.replit-artifact\/$/m);
});

test("mockup sandbox is removed so deployment-focused artifacts stay unambiguous", async () => {
  await assert.rejects(
    access(path.join(repoRoot, "artifacts", "mockup-sandbox", "package.json")),
    /ENOENT/,
  );
});

test("root typecheck only targets deployment-critical workspace packages", async () => {
  const rootPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  const typecheck = rootPackageJson.scripts?.["typecheck"] || "";

  assert.match(typecheck, /@workspace\/api-server/);
  assert.match(typecheck, /@workspace\/status-page/);
  assert.match(typecheck, /@workspace\/scripts/);
  assert.doesNotMatch(typecheck, /\.\/artifacts\/\*\*/);
  assert.doesNotMatch(typecheck, /mockup-sandbox/);
});

test("root package scripts stay focused on direct deployment entrypoints", async () => {
  const rootPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  assert.ok(rootPackageJson.scripts?.["dev"]);
  assert.ok(rootPackageJson.scripts?.["build"]);
  assert.ok(rootPackageJson.scripts?.["build:deploy"]);
  assert.ok(rootPackageJson.scripts?.["start"]);
  assert.ok(rootPackageJson.scripts?.["verify:replit"]);
  assert.ok(rootPackageJson.scripts?.["pack:replit"]);
  assert.ok(rootPackageJson.scripts?.["typecheck"]);
  assert.equal(rootPackageJson.scripts?.["typecheck:libs"], undefined);
  assert.match(rootPackageJson.scripts?.["build:deploy"] || "", /@workspace\/status-page/);
  assert.doesNotMatch(rootPackageJson.scripts?.["build:deploy"] || "", /typecheck/);
});

test("api-server package removes unused db dependencies from install graph", async () => {
  const apiServerPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "artifacts", "api-server", "package.json"), "utf8"),
  ) as {
    dependencies?: Record<string, string>;
  };

  assert.equal(apiServerPackageJson.dependencies?.["@workspace/db"], undefined);
  assert.equal(apiServerPackageJson.dependencies?.["drizzle-orm"], undefined);
});

test("api-server removes the unused Gemini OAI formatter and cookie-parser dependency", async () => {
  const apiServerPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "artifacts", "api-server", "package.json"), "utf8"),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };

  assert.equal(apiServerPackageJson.dependencies?.["cookie-parser"], undefined);
  assert.equal(apiServerPackageJson.devDependencies?.["@types/cookie-parser"], undefined);
  await assert.rejects(
    access(path.join(repoRoot, "artifacts", "api-server", "src", "lib", "format", "gemini.ts")),
    /ENOENT/,
  );
});

test("api-server tsconfig only references packages used by the runtime", async () => {
  const tsconfig = await readFile(path.join(repoRoot, "artifacts", "api-server", "tsconfig.json"), "utf8");

  assert.match(tsconfig, /"path": "\.\.\/\.\.\/lib\/api-zod"/);
  assert.doesNotMatch(tsconfig, /"path": "\.\.\/\.\.\/lib\/db"/);
});

test("workspace package list only includes the two deployable artifacts", async () => {
  const workspaceYaml = await readFile(path.join(repoRoot, "pnpm-workspace.yaml"), "utf8");

  assert.match(workspaceYaml, /^  - artifacts\/api-server$/m);
  assert.match(workspaceYaml, /^  - artifacts\/status-page$/m);
  assert.doesNotMatch(workspaceYaml, /^  - artifacts\/\*$/m);
  assert.doesNotMatch(workspaceYaml, /mockup-sandbox/);
});

test("lockfile no longer advertises mockup sandbox as a workspace importer", async () => {
  const lockfile = await readFile(path.join(repoRoot, "pnpm-lock.yaml"), "utf8");

  assert.doesNotMatch(lockfile, /^  artifacts\/mockup-sandbox:$/m);
});

test(".replitignore excludes local planning notes from deployment payloads", async () => {
  const replitignore = await readFile(path.join(repoRoot, ".replitignore"), "utf8");

  assert.match(replitignore, /^task_plan\.md$/m);
  assert.match(replitignore, /^findings\.md$/m);
  assert.match(replitignore, /^progress\.md$/m);
});

test("scripts package does not expose placeholder commands unrelated to deployment", async () => {
  const scriptsPackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "scripts", "package.json"), "utf8"),
  ) as {
    scripts?: Record<string, string>;
  };

  assert.equal(scriptsPackageJson.scripts?.["hello"], undefined);
});

test("status page removes unused shadcn template files and references", async () => {
  const stalePaths = [
    path.join(repoRoot, "artifacts", "status-page", "components.json"),
    path.join(repoRoot, "artifacts", "status-page", "src", "components", "ui", "button.tsx"),
    path.join(repoRoot, "artifacts", "status-page", "src", "hooks", "use-toast.ts"),
    path.join(repoRoot, "artifacts", "status-page", "src", "lib", "utils.ts"),
  ];

  for (const stalePath of stalePaths) {
    await assert.rejects(access(stalePath), /ENOENT/, `${stalePath} should be removed`);
  }

  const notFound = await readFile(
    path.join(repoRoot, "artifacts", "status-page", "src", "pages", "not-found.tsx"),
    "utf8",
  );

  assert.doesNotMatch(notFound, /components\/ui\/card/);
});

test("status-page package keeps only live dependencies for the current single-page UI", async () => {
  const statusPagePackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "artifacts", "status-page", "package.json"), "utf8"),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const dependencies = {
    ...statusPagePackageJson.dependencies,
    ...statusPagePackageJson.devDependencies,
  };

  assert.equal(dependencies["@workspace/api-client-react"], undefined);
  assert.ok(
    Object.keys(dependencies).every((name) => !name.startsWith("@radix-ui/")),
    "status-page should not keep unused Radix template dependencies",
  );

  for (const packageName of [
    "@hookform/resolvers",
    "class-variance-authority",
    "clsx",
    "cmdk",
    "date-fns",
    "embla-carousel-react",
    "framer-motion",
    "input-otp",
    "next-themes",
    "react-day-picker",
    "react-hook-form",
    "react-icons",
    "react-resizable-panels",
    "recharts",
    "sonner",
    "tailwind-merge",
    "vaul",
    "zod",
  ]) {
    assert.equal(dependencies[packageName], undefined, `${packageName} should be removed from status-page`);
  }

  const statusPageTsconfig = await readFile(
    path.join(repoRoot, "artifacts", "status-page", "tsconfig.json"),
    "utf8",
  );
  assert.doesNotMatch(statusPageTsconfig, /api-client-react/);
});

test("status-page app removes the unused react-query shell", async () => {
  const statusPagePackageJson = JSON.parse(
    await readFile(path.join(repoRoot, "artifacts", "status-page", "package.json"), "utf8"),
  ) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };

  const dependencies = {
    ...statusPagePackageJson.dependencies,
    ...statusPagePackageJson.devDependencies,
  };

  assert.equal(dependencies["@tanstack/react-query"], undefined);

  const appSource = await readFile(
    path.join(repoRoot, "artifacts", "status-page", "src", "App.tsx"),
    "utf8",
  );

  assert.doesNotMatch(appSource, /@tanstack\/react-query/);
  assert.doesNotMatch(appSource, /QueryClientProvider/);
  assert.doesNotMatch(appSource, /new QueryClient/);
});

test("api-server removes legacy anthropic formatter scaffolding after native passthrough migration", async () => {
  const stalePaths = [
    path.join(repoRoot, "artifacts", "api-server", "src", "lib", "format", "anthropic.ts"),
    path.join(repoRoot, "artifacts", "api-server", "src", "lib", "utils.ts"),
    path.join(repoRoot, "artifacts", "api-server", "src", "lib", ".gitkeep"),
    path.join(repoRoot, "artifacts", "api-server", "src", "middlewares", ".gitkeep"),
  ];

  for (const stalePath of stalePaths) {
    await assert.rejects(access(stalePath), /ENOENT/, `${stalePath} should be removed`);
  }

  const geminiRoute = await readFile(
    path.join(repoRoot, "artifacts", "api-server", "src", "routes", "gemini.ts"),
    "utf8",
  );

  assert.doesNotMatch(geminiRoute, /proxyGeminiRequest/);
});

test(".replit pins the one-click deployment commands at the repo root", async () => {
  const replitConfig = await readFile(path.join(repoRoot, ".replit"), "utf8");

  assert.match(replitConfig, /^run = "pnpm dev"$/m);
  assert.match(replitConfig, /^\[deployment\]$/m);
  assert.match(replitConfig, /^build = "pnpm run build:deploy"$/m);
  assert.match(replitConfig, /^run = "pnpm start"$/m);
  assert.match(replitConfig, /^router = "application"$/m);
});

test("api-server production build avoids source maps and dev-only pretty logging transport", async () => {
  const buildScript = await readFile(path.join(repoRoot, "artifacts", "api-server", "build.mjs"), "utf8");

  assert.match(buildScript, /const isProduction = process\.env\.NODE_ENV !== "development";/);
  assert.match(buildScript, /sourcemap: isProduction \? false : "linked"/);
  assert.match(buildScript, /plugins: isProduction\s*\?\s*\[\]\s*:\s*\[/);
  assert.doesNotMatch(buildScript, /esbuildPluginPino\(\{ transports: \["pino-pretty"\] \}\)\s*\],\s*\/\/ Make/s);
});

test(".replit declares required files for GitHub import detection", async () => {
  const replitConfig = await readFile(path.join(repoRoot, ".replit"), "utf8");

  assert.match(replitConfig, /^\[gitHubImport\]$/m);
  assert.match(replitConfig, /^requiredFiles = \["\.replit", "package\.json", "pnpm-workspace\.yaml"\]$/m);
});

test("replit.md tells AI not to patch app code or add extra artifacts just to fix deployment commands", async () => {
  const guide = await readFile(path.join(repoRoot, "replit.md"), "utf8");

  assert.match(guide, /不要为了修复空的 Run command 去改应用代码/);
  assert.match(guide, /不要为了修复发布配置去新增 artifact 或临时脚本/);
});

test("replit.md gives a short deployment acceptance check", async () => {
  const guide = await readFile(path.join(repoRoot, "replit.md"), "utf8");

  assert.match(guide, /GET \/api\/healthz/);
  assert.match(guide, /根路径 `\/` 能打开状态页/);
});

test("README stays short and points deployment readers at replit.md and the Git import entrypoint", async () => {
  const readme = await readFile(path.join(repoRoot, "README.md"), "utf8");

  assert.match(readme, /replit\.md/);
  assert.match(readme, /Build command: `pnpm run build:deploy`/);
  assert.match(readme, /Run command: `pnpm start`/);
  assert.match(readme, /Git 导入到 Replit/);
  assert.doesNotMatch(readme, /REPLIT_UPLOAD_PROMPT\.txt/);
  assert.doesNotMatch(readme, /REPLIT_FAST_START_PROMPT\.txt/);
  assert.doesNotMatch(readme, /一轮对话版/);
});

test("upload prompt tells AI to work from the current Git-imported project root", async () => {
  const prompt = await readFile(path.join(repoRoot, "REPLIT_UPLOAD_PROMPT.txt"), "utf8");

  assert.match(prompt, /通过 Git 导入/);
  assert.match(prompt, /直接使用当前 Replit 项目根目录/);
  assert.match(prompt, /只确认当前 `?\.replit`? 满足/);
  assert.match(prompt, /run = pnpm dev/);
  assert.match(prompt, /deployment build = pnpm run build:deploy/);
  assert.match(prompt, /deployment run = pnpm start/);
  assert.doesNotMatch(prompt, /zip/);
  assert.doesNotMatch(prompt, /解压/);
});

test("runtime upload release is a minimal runtime-only package", async () => {
  const uploadRoot = path.join(repoRoot, "release", "Asset-Attachments-replit-upload");

  await access(path.join(uploadRoot, "package.json"));
  await access(path.join(uploadRoot, "server", "start.mjs"));
  await access(path.join(uploadRoot, "server", "verify-replit.mjs"));
  await access(path.join(uploadRoot, "public", "index.html"));
  await assert.rejects(access(path.join(uploadRoot, ".replit")), /ENOENT/);
  await assert.rejects(access(path.join(uploadRoot, "artifacts")), /ENOENT/);
  await assert.rejects(access(path.join(uploadRoot, "lib")), /ENOENT/);
  await assert.rejects(access(path.join(uploadRoot, "scripts")), /ENOENT/);
});

test("runtime fast-start release keeps the same minimal layout and includes .replit", async () => {
  const fastRoot = path.join(repoRoot, "release", "Asset-Attachments-replit-fast-start");

  await access(path.join(fastRoot, ".replit"));
  await access(path.join(fastRoot, "package.json"));
  await access(path.join(fastRoot, "server", "start.mjs"));
  await access(path.join(fastRoot, "server", "verify-replit.mjs"));
  await access(path.join(fastRoot, "public", "index.html"));
  await assert.rejects(access(path.join(fastRoot, "artifacts")), /ENOENT/);
  await assert.rejects(access(path.join(fastRoot, "lib")), /ENOENT/);
  await assert.rejects(access(path.join(fastRoot, "scripts")), /ENOENT/);
});

test("replit.md starts with a one-shot instruction block for Replit AI", async () => {
  const guide = await readFile(path.join(repoRoot, "replit.md"), "utf8");

  assert.match(guide, /如果你只能做一轮对话/);
  assert.match(guide, /不要自己推断其它部署拓扑/);
  assert.match(guide, /通过 Git 导入/);
  assert.match(guide, /Deploy 面板固定填写/);
  assert.match(guide, /Build command: `pnpm run build:deploy`/);
  assert.match(guide, /Run command: `pnpm start`/);
  assert.doesNotMatch(guide, /zip/);
  assert.doesNotMatch(guide, /解压/);
});

test("status page warns that Gemini does not support OpenAI chat completions", async () => {
  const page = await readFile(
    path.join(repoRoot, "artifacts", "status-page", "src", "pages", "status-page.tsx"),
    "utf8",
  );

  assert.match(page, /Gemini/i);
  assert.match(page, /\/openai\/chat\/completions/);
  assert.match(page, /generateContent/);
});

test("replit-facing docs describe Anthropic and Gemini as Replit integrations", async () => {
  const files = [
    path.join(repoRoot, "README.md"),
    path.join(repoRoot, "replit.md"),
    path.join(repoRoot, "REPLIT_UPLOAD_PROMPT.txt"),
    path.join(repoRoot, "REPLIT_FAST_START_PROMPT.txt"),
    path.join(repoRoot, "scripts", "build-replit-runtime.mjs"),
    path.join(repoRoot, "artifacts", "status-page", "src", "pages", "status-page.tsx"),
  ];

  for (const file of files) {
    const content = await readFile(file, "utf8");
    assert.match(content, /Anthropic.*Replit integration/i, `${file} should mention Anthropic Replit integration`);
    assert.match(content, /Gemini.*Replit integration/i, `${file} should mention Gemini Replit integration`);
    assert.doesNotMatch(content, /GEMINI_API_KEY/, `${file} should not tell Replit users to set GEMINI_API_KEY directly`);
  }
});
